[package]
name = "waystone-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
switch = ["waystone-core/switch"]
3ds = ["waystone-core/3ds"]

[dependencies]
waystone-core = { path = "../core" }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
spin = "0.9"

[dev-dependencies]
cbindgen = "0.29"
