#ifndef WAYSTONE_H
#define WAYSTONE_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct WsBuf {
    uint8_t *ptr;
    uintptr_t len;
} WsBuf;

typedef Vault WsVault;

 char *ws_jksv_normalize(const char *system, const char *raw_tree_json);

 char *ws_jksv_to_native(const char *normalized_save_json);

 char *ws_mgba_normalize(const char *system, const char *raw_tree_json);

 char *ws_mgba_to_native(const char *normalized_save_json);

 char *ws_twilight_normalize(const char *raw_tree_json);

 char *ws_twilight_to_native(const char *normalized_save_json);

/**
 * # Safety
 * `buf.ptr` must have been allocated by `WsBuf::from_vec` or be null.
 */
 void ws_buf_free(struct WsBuf buf);

/**
 * # Safety
 * `s` must have been returned by `owned_c_string` or be null.
 */
 void ws_string_free(char *s);

 char *ws_fold_heads(const char *heads_json);


char *ws_three_way_sync(const char *local_hash,
                        const char *base_hash,
                        const char *head_hash,
                        const char *local_mtime,
                        const char *head_mtime,
                        int policy);


char *ws_decide_pull(const char *local_hash,
                     const char *local_mtime,
                     const char *all_heads_json,
                     const char *this_device_id,
                     int policy);


WsVault *ws_vault_init(const char *passphrase,
                       struct WsBuf *out_recovery_hex,
                       struct WsBuf *out_keys_json);

 WsVault *ws_vault_unlock_pass(const char *passphrase, const uint8_t *keys_json, uintptr_t n);

 WsVault *ws_vault_unlock_recovery(const char *recovery_hex, const uint8_t *keys_json, uintptr_t n);

 struct WsBuf ws_vault_encrypt_blob(const WsVault *vault, const uint8_t *data, uintptr_t len);

 struct WsBuf ws_vault_decrypt_blob(const WsVault *vault, const uint8_t *data, uintptr_t len);

 struct WsBuf ws_vault_encrypt_heads(const WsVault *vault, const uint8_t *data, uintptr_t len);

 struct WsBuf ws_vault_decrypt_heads(const WsVault *vault, const uint8_t *data, uintptr_t len);

 char *ws_vault_blob_name(const WsVault *vault, const char *hash);

 char *ws_vault_path_segment(const WsVault *vault, const char *name);

 void ws_vault_free(WsVault *vault);

/**
 * # Safety
 * The returned pointer is valid until the next call that modifies `LAST_ERROR`
 * (process-global since the `thread_local!` -> `spin::Mutex` migration).
 * Callers must copy the string before any subsequent FFI call that could set an error.
 */
 const char *ws_last_error(void);

 struct WsBuf ws_canonical_zip(const char *files_json);

 char *ws_unzip(const uint8_t *data, uintptr_t len);

 char *ws_content_hash(const uint8_t *data, uintptr_t len);

 char *ws_file_hash(const uint8_t *data, uintptr_t len);

 char *ws_package(const char *normalized_save_json, struct WsBuf *out_zip);

#endif  /* WAYSTONE_H */
